import type {
  Listing,
  ListingStats,
  ReviewListing,
  StaffStats,
  AICheck,
  ChecklistItem,
  FeedbackItem,
  User,
} from "./types"

export const mockUser: User = {
  id: "user-1",
  email: "john@example.com",
  name: "John Doe",
  role: "seller",
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
  phone: "+1 234 567 890",
  type: "owner",
}

export const mockStaffUser: User = {
  id: "staff-1",
  email: "sarah@proplist.com",
  name: "Sarah Chen",
  role: "staff",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&crop=face",
}

export const mockListingStats: ListingStats = {
  total: 24,
  published: 18,
  pending: 4,
  rejected: 2,
  draft: 0,
}

export const mockStaffStats: StaffStats = {
  totalQueue: 89,
  assignedToMe: 12,
  reviewedToday: 8,
  avgReviewTime: "3.2 min",
}

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    title: "Modern 3-Bedroom Apartment in Downtown",
    description:
      "Beautiful modern apartment with stunning city views. Features include hardwood floors, stainless steel appliances, and a private balcony. Located in the heart of downtown with easy access to public transportation, restaurants, and shopping.",
    propertyType: "apartment",
    transactionType: "sale",
    price: 450000,
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: "123 Main Street, Apt 4B",
      city: "New York",
      district: "Manhattan",
      ward: "Chelsea",
      lat: 40.7128,
      lng: -74.006,
    },
    images: [
      {
        id: "img-1",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200",
        alt: "Living room",
        isCover: true,
        order: 0,
      },
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=200",
        alt: "Kitchen",
        isCover: false,
        order: 1,
      },
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=200",
        alt: "Bedroom",
        isCover: false,
        order: 2,
      },
    ],
    videos: [],
    amenities: ["Pool", "Gym", "Parking", "Security", "Elevator"],
    features: ["Furnished", "Pet-friendly", "Newly Built"],
    status: "published",
    sellerId: "user-1",
    seller: mockUser,
    views: 156,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    publishedAt: "2024-01-16T14:00:00Z",
    yearBuilt: 2022,
    floor: 4,
    direction: "South",
    legalStatus: "Red Book",
  },
  {
    id: "listing-2",
    title: "Spacious Family House with Garden",
    description:
      "Perfect family home with a large backyard and modern amenities. The house features 4 bedrooms, 3 bathrooms, a gourmet kitchen, and a two-car garage. Beautiful landscaping and a great neighborhood.",
    propertyType: "house",
    transactionType: "sale",
    price: 850000,
    area: 280,
    bedrooms: 4,
    bathrooms: 3,
    location: {
      address: "456 Oak Avenue",
      city: "Los Angeles",
      district: "Beverly Hills",
      ward: "Beverly Grove",
      lat: 34.0736,
      lng: -118.4004,
    },
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=200",
        alt: "House exterior",
        isCover: true,
        order: 0,
      },
    ],
    videos: [],
    amenities: ["Garden", "Parking", "Security"],
    features: ["Renovated"],
    status: "pending_staff_review",
    sellerId: "user-1",
    seller: mockUser,
    views: 89,
    createdAt: "2024-01-18T09:15:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
    yearBuilt: 2018,
    floor: 1,
    direction: "East",
    legalStatus: "Pink Book",
  },
  {
    id: "listing-3",
    title: "Cozy Studio for Rent Near University",
    description:
      "Ideal for students or young professionals. This cozy studio apartment is located just minutes from the university campus. Includes utilities and high-speed internet.",
    propertyType: "apartment",
    transactionType: "rental",
    price: 1200,
    area: 45,
    bedrooms: 0,
    bathrooms: 1,
    location: {
      address: "789 College Road, Unit 2",
      city: "Boston",
      district: "Cambridge",
      ward: "Harvard Square",
      lat: 42.3736,
      lng: -71.1097,
    },
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=200",
        alt: "Studio interior",
        isCover: true,
        order: 0,
      },
    ],
    videos: [],
    amenities: ["Elevator", "Security"],
    features: ["Furnished"],
    status: "ai_rejected",
    sellerId: "user-1",
    seller: mockUser,
    views: 45,
    createdAt: "2024-01-20T14:45:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
    yearBuilt: 2015,
    floor: 2,
    direction: "West",
    legalStatus: "Contract",
  },
  {
    id: "listing-4",
    title: "Luxury Villa with Ocean View",
    description:
      "Stunning luxury villa overlooking the ocean. Features include infinity pool, private beach access, home theater, and wine cellar. Perfect for those seeking the ultimate in coastal living.",
    propertyType: "villa",
    transactionType: "sale",
    price: 2500000,
    area: 450,
    bedrooms: 5,
    bathrooms: 4,
    location: {
      address: "1 Ocean Drive",
      city: "Miami",
      district: "Miami Beach",
      ward: "South Beach",
      lat: 25.7617,
      lng: -80.1918,
    },
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=200",
        alt: "Villa exterior",
        isCover: true,
        order: 0,
      },
    ],
    videos: [],
    amenities: ["Pool", "Gym", "Parking", "Security", "Garden", "Balcony"],
    features: ["Furnished", "Newly Built"],
    status: "published",
    sellerId: "user-1",
    seller: mockUser,
    views: 324,
    createdAt: "2024-01-10T11:00:00Z",
    updatedAt: "2024-01-10T11:00:00Z",
    publishedAt: "2024-01-11T09:00:00Z",
    yearBuilt: 2023,
    floor: 1,
    direction: "North",
    legalStatus: "Red Book",
  },
  {
    id: "listing-5",
    title: "Commercial Office Space in Business District",
    description:
      "Prime office space in the heart of the business district. Open floor plan with modern finishes. Includes conference rooms, reception area, and dedicated parking.",
    propertyType: "office",
    transactionType: "rental",
    price: 5500,
    area: 200,
    bedrooms: 0,
    bathrooms: 2,
    location: {
      address: "500 Business Plaza, Suite 300",
      city: "Chicago",
      district: "Loop",
      ward: "Financial District",
      lat: 41.8781,
      lng: -87.6298,
    },
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=200",
        alt: "Office interior",
        isCover: true,
        order: 0,
      },
    ],
    videos: [],
    amenities: ["Elevator", "Security", "Parking"],
    features: [],
    status: "draft",
    sellerId: "user-1",
    seller: mockUser,
    views: 0,
    createdAt: "2024-01-22T16:30:00Z",
    updatedAt: "2024-01-22T16:30:00Z",
    yearBuilt: 2020,
    floor: 3,
    direction: "East",
    legalStatus: "Contract",
  },
]

export const mockReviewQueue: ReviewListing[] = [
  {
    id: "review-1",
    title: "Spacious Family House with Garden",
    seller: { name: "John Doe", type: "individual" },
    priority: "high",
    waitTime: 48,
    submittedAt: "2024-01-20T10:00:00Z",
    propertyType: "house",
    price: 850000,
    thumbnailUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=200",
  },
  {
    id: "review-2",
    title: "Modern Loft in Arts District",
    seller: { name: "Jane Smith", type: "broker" },
    priority: "medium",
    waitTime: 24,
    submittedAt: "2024-01-21T14:30:00Z",
    assignedTo: "staff-1",
    propertyType: "apartment",
    price: 380000,
    thumbnailUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200",
  },
  {
    id: "review-3",
    title: "Beachfront Condo",
    seller: { name: "Beach Properties Inc", type: "broker" },
    priority: "low",
    waitTime: 12,
    submittedAt: "2024-01-22T09:15:00Z",
    propertyType: "apartment",
    price: 620000,
    thumbnailUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=200",
  },
  {
    id: "review-4",
    title: "Downtown Office Building",
    seller: { name: "Commercial Real Estate Co", type: "broker" },
    priority: "high",
    waitTime: 36,
    submittedAt: "2024-01-20T16:45:00Z",
    propertyType: "office",
    price: 1200000,
    thumbnailUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=200",
  },
  {
    id: "review-5",
    title: "Suburban Family Home",
    seller: { name: "Robert Johnson", type: "individual" },
    priority: "medium",
    waitTime: 18,
    submittedAt: "2024-01-21T11:00:00Z",
    propertyType: "house",
    price: 495000,
    thumbnailUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=200",
  },
]

export const mockAIChecks: AICheck[] = [
  {
    type: "image_quality",
    status: "pass",
    confidence: 95,
    details: "All images meet quality standards. Resolution and clarity are excellent.",
  },
  {
    type: "duplicate",
    status: "pass",
    confidence: 98,
    details: "No duplicate listings found in the database.",
  },
  {
    type: "price_anomaly",
    status: "warning",
    confidence: 72,
    details:
      "Price is 15% above market average for this area. May be justified by property features.",
  },
  {
    type: "content_policy",
    status: "pass",
    confidence: 99,
    details: "Content meets all policy guidelines. No violations detected.",
  },
]

export const mockChecklist: ChecklistItem[] = [
  { id: "check-1", label: "Images are authentic (not from other projects)", checked: false, required: true },
  { id: "check-2", label: "Price is reasonable for the area", checked: false, required: true },
  { id: "check-3", label: "Legal documents are valid", checked: false, required: true },
  { id: "check-4", label: "Description is accurate and not misleading", checked: false, required: true },
  { id: "check-5", label: "Address is verified (checked on Google Maps)", checked: false, required: true },
  { id: "check-6", label: "Seller identity is verified", checked: false, required: false },
]

export const mockFeedbackItems: FeedbackItem[] = [
  {
    id: "fb-1",
    category: "images",
    field: "Cover Image",
    severity: "error",
    message: "The cover image appears to be watermarked or from a stock photo site.",
    suggestedAction: "Please upload original photos of the property taken by yourself or a professional photographer.",
    affectedField: "images",
  },
  {
    id: "fb-2",
    category: "images",
    field: "Image Count",
    severity: "warning",
    message: "Only 3 images provided. Listings with more photos receive 40% more views.",
    suggestedAction: "Add at least 10 images showing different areas of the property including all rooms, kitchen, bathrooms, and exterior.",
    affectedField: "images",
  },
  {
    id: "fb-3",
    category: "description",
    field: "Property Description",
    severity: "error",
    message: "Description contains placeholder text or copy-pasted content from another listing.",
    suggestedAction: "Write a unique description that highlights the specific features and benefits of this property.",
    affectedField: "description",
  },
  {
    id: "fb-4",
    category: "price",
    field: "Listed Price",
    severity: "warning",
    message: "The price appears to be 25% below market average for similar properties in this area.",
    suggestedAction: "Review the price and ensure it accurately reflects the property value. If intentional, consider adding a note explaining the pricing.",
    affectedField: "price",
  },
  {
    id: "fb-5",
    category: "legal",
    field: "Legal Status",
    severity: "info",
    message: "Legal status selected as 'Contract' which may limit buyer interest.",
    suggestedAction: "If you have additional legal documentation, please specify in the description or upload supporting documents.",
    affectedField: "legalStatus",
  },
]
