import { SearchListing } from "./types";

export const mockSearchListings: SearchListing[] = [
  {
    id: "search-listing-1",
    title: "Modern 3-Bedroom Apartment in Downtown",
    description:
      "Beautiful modern apartment with stunning city views. Features include hardwood floors, stainless steel appliances, and a private balcony. Located in the heart of downtown with easy access to public transportation, restaurants, and shopping.",
    propertyType: "apartment",
    transactionType: "sale",
    location: {
      country: "United States",
      province: "New York",
      district: "Manhattan",
      ward: "Chelsea",
      streetAddress: "123 Main Street, Apt 4B",
      postalCode: "10001",
      coordinates: {
        lat: 40.7128,
        lng: -74.006,
      },
    },
    propertyDetails: {
      bedrooms: 3,
      bathrooms: 2,
      areaSqm: 120,
      yearBuilt: 2022,
      floorNumber: 4,
      totalFloors: 10,
      direction: "South",
      features: ["Furnished", "Pet-friendly", "Newly Built"],
    },
    pricing: {
      price: 450000,
      currency: "USD",
      formattedPrice: "$450,000",
      pricePerSqm: 3750,
    },
    legal: {
      legalStatus: "Red Book",
      ownershipType: "Freehold",
    },
    media: {
      images: [
        {
          id: "img-1",
          url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200",
          alt: "Living room",
          isCover: true,
          order: 0,
        },
        {
          id: "img-2",
          url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=200",
          alt: "Kitchen",
          isCover: false,
          order: 1,
        },
        {
          id: "img-3",
          url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=200",
          alt: "Bedroom",
          isCover: false,
          order: 2,
        },
      ],
      videos: [],
    },
    agent: {
      id: "agent-1",
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      phone: "+1 234 567 890",
    },
    status: "published",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "search-listing-2",
    title: "Spacious Family House with Garden",
    description:
      "Perfect family home with a large backyard and modern amenities. The house features 4 bedrooms, 3 bathrooms, a gourmet kitchen, and a two-car garage. Beautiful landscaping and a great neighborhood.",
    propertyType: "house",
    transactionType: "sale",
    location: {
      country: "United States",
      province: "California",
      district: "Beverly Hills",
      ward: "Beverly Grove",
      streetAddress: "456 Oak Avenue",
      postalCode: "90210",
      coordinates: {
        lat: 34.0736,
        lng: -118.4004,
      },
    },
    propertyDetails: {
      bedrooms: 4,
      bathrooms: 3,
      areaSqm: 280,
      yearBuilt: 2018,
      floorNumber: 1,
      totalFloors: 2,
      direction: "East",
      features: ["Renovated"],
    },
    pricing: {
      price: 850000,
      currency: "USD",
      formattedPrice: "$850,000",
      pricePerSqm: 3035.71,
    },
    legal: {
      legalStatus: "Pink Book",
      ownershipType: "Leasehold",
    },
    media: {
      images: [
        {
          id: "img-4",
          url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=200",
          alt: "House exterior",
          isCover: true,
          order: 0,
        },
      ],
    },
    agent: {
      id: "agent-1",
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      phone: "+1 234 567 890",
    },
    status: "pending",
    createdAt: "2024-01-18T09:15:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
  },
  {
    id: "search-listing-3",
    title: "Cozy Studio for Rent Near University",
    description:
      "Ideal for students or young professionals. This cozy studio apartment is located just minutes from the university campus. Includes utilities and high-speed internet.",
    propertyType: "apartment",
    transactionType: "rent",
    location: {
      country: "United States",
      province: "Massachusetts",
      district: "Cambridge",
      ward: "Harvard Square",
      streetAddress: "789 College Road, Unit 2",
      postalCode: "02138",
      coordinates: {
        lat: 42.3736,
        lng: -71.1097,
      },
    },
    propertyDetails: {
      bedrooms: 0,
      bathrooms: 1,
      areaSqm: 45,
      yearBuilt: 2015,
      floorNumber: 2,
      totalFloors: 5,
      direction: "West",
      features: ["Furnished"],
    },
    pricing: {
      price: 1200,
      currency: "USD",
      formattedPrice: "$1,200",
      pricePerSqm: 26.67,
    },
    legal: {
      legalStatus: "Contract",
    },
    media: {
      images: [
        {
          id: "img-5",
          url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=200",
          alt: "Studio interior",
          isCover: true,
          order: 0,
        },
      ],
    },
    agent: {
      id: "agent-1",
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      phone: "+1 234 567 890",
    },
    status: "published",
    createdAt: "2024-01-20T14:45:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
  },
  {
    id: "search-listing-4",
    title: "Luxury Villa with Ocean View",
    description:
      "Stunning luxury villa overlooking the ocean. Features include infinity pool, private beach access, home theater, and wine cellar. Perfect for those seeking the ultimate in coastal living.",
    propertyType: "villa",
    transactionType: "sale",
    location: {
      country: "United States",
      province: "Florida",
      district: "Miami Beach",
      ward: "South Beach",
      streetAddress: "1 Ocean Drive",
      postalCode: "33139",
      coordinates: {
        lat: 25.7617,
        lng: -80.1918,
      },
    },
    propertyDetails: {
      bedrooms: 5,
      bathrooms: 4,
      areaSqm: 450,
      yearBuilt: 2023,
      floorNumber: 1,
      totalFloors: 3,
      direction: "North",
      features: ["Furnished", "Newly Built", "Infinity Pool", "Ocean View"],
    },
    pricing: {
      price: 2500000,
      currency: "USD",
      formattedPrice: "$2,500,000",
      pricePerSqm: 5555.56,
    },
    legal: {
      legalStatus: "Red Book",
      ownershipType: "Freehold",
    },
    media: {
      images: [
        {
          id: "img-6",
          url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=200",
          alt: "Villa exterior",
          isCover: true,
          order: 0,
        },
      ],
    },
    agent: {
      id: "agent-1",
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      phone: "+1 234 567 890",
    },
    status: "published",
    createdAt: "2024-01-10T11:00:00Z",
    updatedAt: "2024-01-10T11:00:00Z",
  },
  {
    id: "search-listing-5",
    title: "Commercial Office Space in Business District",
    description:
      "Prime office space in the heart of the business district. Open floor plan with modern finishes. Includes conference rooms, reception area, and dedicated parking.",
    propertyType: "commercial",
    transactionType: "rent",
    location: {
      country: "United States",
      province: "Illinois",
      district: "Loop",
      ward: "Financial District",
      streetAddress: "500 Business Plaza, Suite 300",
      postalCode: "60606",
      coordinates: {
        lat: 41.8781,
        lng: -87.6298,
      },
    },
    propertyDetails: {
      bedrooms: 0,
      bathrooms: 2,
      areaSqm: 200,
      yearBuilt: 2020,
      floorNumber: 3,
      totalFloors: 25,
      direction: "East",
      features: [],
    },
    pricing: {
      price: 5500,
      currency: "USD",
      formattedPrice: "$5,500/mo",
      pricePerSqm: 27.5,
    },
    legal: {
      legalStatus: "Contract",
    },
    media: {
      images: [
        {
          id: "img-7",
          url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
          thumbnailUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=200",
          alt: "Office interior",
          isCover: true,
          order: 0,
        },
      ],
    },
    agent: {
      id: "agent-1",
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      phone: "+1 234 567 890",
    },
    status: "published",
    createdAt: "2024-01-22T16:30:00Z",
    updatedAt: "2024-01-22T16:30:00Z",
  },
];
